App\Entity\Post:
    operations:
        ApiPlatform\Metadata\GetCollection:
            method: 'GET'
            path: '/posts'
            filters:
                - post.filter_tag
            normalizationContext:
                groups: ['post:read']
        ApiPlatform\Metadata\POST:
            method: 'POST'
            denormalizationContext:
                groups: ['post:write']
            path: '/posts'
            filters:
                - post.filter_tag
        ApiPlatform\Metadata\Delete: ~                           