App\Entity\Tag:
    operations:
        ApiPlatform\Metadata\GetCollection:
            filters: ['tag.search_filter']
        ApiPlatform\Metadata\POST:
            method: 'POST'
            denormalizationContext:
                groups: ['tag:write']
            path: '/tags'