version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
  
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./test_project:/var/www/test_project  
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_network
  
  php:
    build:
      context: .                    
      dockerfile: ./php/dockerfile    
    container_name: app
    volumes:
      - ./ini/php.ini:/usr/local/etc/php/conf.d/custom-php.ini   
      - ./test_project:/var/www/test_project
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
