FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zlib1g-dev \
    libmariadb-dev \
    libicu-dev \
    libxml2-dev \
    git \
    curl \
    ca-certificates \
    gnupg \    
    unzip \
    && docker-php-ext-install pdo pdo_mysql mysqli opcache \
    && docker-php-ext-enable opcache \
    && docker-php-ext-enable opcache \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY ./test_project/package*.json ./
COPY ./test_project/composer.json ./test_project/composer.lock* ./
COPY ./test_project/ .

WORKDIR /var/www/test_project
